Feature/iot 11 1/create alarm
SEP4Y-S24/iot pull request #27
Opened 2024-05-10 12:19 UTC by THEWhiteArrow

add:
- create alarm
- delete alarm
- native wrapper for delay function so it can be tested
- fix no perfect structure of external screen update time
- add scheduler to perform the tasks

2024-05-10 13:10 UTC, JakubCerovsky approved these changes
Great job, looks good just commented some minor things to maybe discuss or clean up. 👌🏼 all documentation is about creating alarm so naming it in code to set feels a bit unreasonable…

2024-05-10 13:10 UTC, JakubCerovsky commented on lib/controllers/alarm.c
> +        // log_info("Alarm is now");
Cleanup.

2024-05-10 13:10 UTC, JakubCerovsky commented on lib/controllers/alarm.c
> +    // log_info("Checking alarm");
Cleanup

2024-05-10 13:10 UTC, JakubCerovsky commented on lib/comm/ccp_message_handler.c
> +void ccp_handle_set_alarm(char *message);
Set alarm or create alarm?

2024-05-10 14:39 UTC, RubberDuck2307 requested changes

2024-05-10 14:39 UTC, RubberDuck2307 commented on lib/drivers/external_screen.c
> +void external_screen_update_time_from_clock()
can this method be please moved to display_controller. The drivers should be only operating the hardware, not handling logic such as getting the values from other files.

2024-05-10 14:52 UTC, RubberDuck2307 requested changes

2024-05-10 14:52 UTC, RubberDuck2307 commented on src/main.c
> +	scheduler_add_task(clock_update_time, clock_minute_interval);
Can you please move adding the tasks to the `start() ` function of state_coordinator.

2024-05-10 14:52 UTC, RubberDuck2307 commented on src/main.c
> +	scheduler_add_task(clock_update_time, clock_minute_interval);
I would like to keep separated the initialization that does not have a functionality from rest of the code that actually does something.

2024-05-13 08:36 UTC, RubberDuck2307 approved these changes

2024-05-13 08:38 UTC, merged